READ FIRSTNAME$, LASTNAME$, SALARY
DO WHILE FIRSTNAME$ <> "EOF"
    '   READ FIRSTNAME$, LASTNAME$, SALARY
    '    IF FIRSTNAME$ = "FRANK" THEN FRANKCOUNT = FRANKCOUNT + 1
    '    IF FIRSTNAME$ = "MARY" THEN MARYCOUNT = MARYCOUNT + 1
    SALARY.SUM = SALARY.SUM + SALARY
    PRINT FIRSTNAME$, LASTNAME$, "THEY MAKE", SALARY
    READ FIRSTNAME$, LASTNAME$, SALARY
LOOP
'PRINT "SALARY SUM IS", SALARY.SUM
'PRINT "FRANK APPEARED", FRANKCOUNT, "TIMES"
'PRINT "MARY APPEARED", MARYCOUNT, "TIMES"
DATA FRANK,THOMPSON,50
DATA MARY,SMITH,30
DATA EOF,ABC,50


